### ISSUE TITLE
doesn;t compile on MAC OS X Tiger 10.4.11

### ISSUE THREAD

**Issue by GoogleCodeExporter** [ashish21590/redis#70]
```
What steps will reproduce the problem?
1. /usr/src/redis-1.01 $ sudo make
2.
3.

What is the expected output? What do you see instead?
cc -c -std=c99 -pedantic -O2 -Wall -W -g -rdynamic -ggdb   redis.c
i686-apple-darwin8-gcc-4.0.1: unrecognized option '-rdynamic'
redis.c:44:22: error: execinfo.h: No such file or directory
redis.c: In function 'updateSlavesWaitingBgsave':
redis.c:3980: error: storage size of 'buf' isn't known
redis.c:3988: warning: implicit declaration of function 'fstat64'
redis.c:3980: warning: unused variable 'buf'
redis.c: In function 'getMcontextEip':
redis.c:4309: error: 'struct mcontext' has no member named '__ss'
redis.c: In function 'segvHandler':
redis.c:4361: warning: implicit declaration of function 'backtrace'
redis.c:4366: warning: implicit declaration of function 'backtrace_symbols'
redis.c:4366: warning: assignment makes pointer from integer without a cast
make: *** [redis.o] Error 1

redis 1.01  on MAC book OS X Tiger 10.4.11

tried with mac ports same error

thanks for help


```

Original issue reported on code.google.com by `nathan.sharkey` on 9 Oct 2009 at 3:19

**Comment by GoogleCodeExporter** [comment]
```
Tiger will not be supported unfortunately. Thx for reporting.
```

Original comment by `anti...@gmail.com` on 23 Oct 2009 at 12:39
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
```
for people out there that can't upgrade right now but plan to use an untested,
unsupported, probably broken redis for fun/development, the attached patch fixes
compilation on tiger (except for a few warnings related to -rdynamic not being
recognized).

mecbuc:~/Dev/redis rff$ gcc -v
Using built-in specs.
Target: i686-apple-darwin8
Configured with: /var/tmp/gcc/gcc-5370~2/src/configure --disable-checking
-enable-werror --prefix=/usr --mandir=/share/man
--enable-languages=c,objc,c++,obj-c++
--program-transform-name=/^[cg][^.-]*$/s/$/-4.0/
--with-gxx-include-dir=/include/c++/4.0.0 --with-slibdir=/usr/lib
--build=powerpc-apple-darwin8 --with-arch=nocona --with-tune=generic
--program-prefix= --host=i686-apple-darwin8 --target=i686-apple-darwin8
Thread model: posix
gcc version 4.0.1 (Apple Computer, Inc. build 5370)


mecbuc:~/Dev/redis rff$ make test 
....
Test result
tests pass:
130 tests, 130 passed, 0 failed

Applied on top of 

commit a96ffc6641ae91e1291e30a4af7570d6aa0c5945
Author: antirez <antirez@gmail.com>
Date:   Sat Nov 21 16:40:08 2009 +0100

    version incremented up to 1.06


Once again: this does not make tiger supported, and maybe breaks the build on 
10.5 as
I changed the fstat-related #ifdef. Use at your own risk.
```

Original comment by `rff....@gmail.com` on 21 Nov 2009 at 4:19

Attachments:
- [osx_tiger_support.patch](https://storage.googleapis.com/google-code-attachments/redis/issue-70/comment-2/osx_tiger_support.patch)
